# Generated by Django 5.0.7 on 2024-08-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
                ("ticker", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="trade",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="user",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
        migrations.DeleteModel(
            name="Trade",
        ),
    ]
